apiVersion: v1
kind: Service
metadata:
  labels:
    app: convertx
  name: convertx
  namespace: media
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: convertx
  type: ClusterIP
