apiVersion: v1
kind: Service
metadata:
  labels:
    app: its-mytabs
  name: its-mytabs
spec:
  ports:
    - port: 47777
      protocol: TCP
      targetPort: 47777
  selector:
    app: its-mytabs
  type: ClusterIP
