apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: its-mytabs
  namespace: tabs
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - tabs.christophervestman.com
      secretName: its-mytabs-tls
  rules:
    - host: tabs.christophervestman.com
      http:
        paths:
          - backend:
              service:
                name: its-mytabs
                port:
                  number: 47777
            path: /
            pathType: Prefix
