apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actualbudget
  # - audiobookshelf
  - convertx
  - discord-bot
  - glance
  - immich
  - its-mytabs
  - jellyfin
  # - linkding
  - linkwarden
  - mealie
  - namespaces
  - n8n
  - paperless-ngx
  - pgadmin
  - prowlarr
  - qbittorrent
  - radarr
  - sonarr
  - wallos
