apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kps-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: kps-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin-user
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-pass
