apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kps-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: az-kv-store
    kind: ClusterSecretStore
  target:
    name: kps-secrets
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_ADMIN_PASS
      remoteRef:
        key: grafana-admin-pass
